### ISSUE TITLE
Album not working

### ISSUE THREAD

**Issue by melaww** [thexavier666/youtube-mp3-split#5]
Your script fails with this error whenever I use "album" as last argument.
It works fine if the last argument is "mixtape", and it will tag the files as if it would be an album.

```
Traceback (most recent call last):
  File "time_split.py", line 94, in <module>
    main()
  File "time_split.py", line 86, in main
    make_songs(main_mp3_file, row[0], row[1], row[2], row[3], row[4], row[5])
IndexError: list index out of range
```

**Comment by thexavier666** [comment]
I removed the concept of mixtape and album since it has become confusing to me as well. No need to add the extra argument `mixtape/album` henceforth :)
I have added a new example in the README. Should be working now.
